### ISSUE TITLE
Ханш татагдахгүй байна. 

### ISSUE THREAD

**Issue by baigal26** [Ankhbayar/monxansh#17]
Сайн байна уу?

Монгол банкны сайт шинэчлэгдснээс хойш татахгүй байж байгаад 9нд нэг удаа татсан байснаа өнөөдөр буюу 10нд бас татагдаагүй байна. Засвар хийж өгөх боломжтой болов уу? 

Мэндчилсэн, 
Байнгын хэрэглэгч

**Comment by Ankhbayar** [comment]
баяраллаа. Өөрчлөлтийн засварыг оруулсан байгаа.
